### ISSUE TITLE
Blacklisted commands still show up in completions

### ISSUE THREAD

**Issue by matthoffman** [facebookincubator/python-nubia#16]
Maybe I'm misunderstanding what blacklisted commands are for, but I was surprised to see that the blacklisted command in the example project still showed up in the list of available commands, and in tab completion, etc. It won't actually be executed, but it's still visible. 
Is that desired behavior?  

If not, I'm happy to submit a PR ... perhaps excluding it in `CommandRegistry.registerCommand`? But more likely I'm just misunderstanding the purpose of the blacklist.

**Comment by ylectric** [comment]
Hi @matthoffman and thanks for noticing this!
I'm surprised to see this issue being open without any response for 1.5 months, but I was on PTO in November, I swear 🙂
It makes sense to me to exclude blacklisted commands from available completions, so a PR is absolutely welcome.

**Comment by AhmedSoliman** [comment]
I think our blacklisting mechanism works like "soft-blacklisting" (gray-listing?) rather than a hard blacklist. Blacklisting a command does not equal to removing the command, it's meant to give a clear signal that a command exists but is currently blacklisted because maybe it's dangerous.

In this semantic, it makes sense to see this command normally in help and auto completion lists. If you want this behavior to change, I would accept a PR that would make this behavior configurable.
